name: CI
on:
    push:
          branches: [My_Modif]
jobs:
      build:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout
          uses: actions/checkout@v5
            
        - name: installation dependences
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake
            sudo apt-get install libsdl2-ttf-2.0-0 libsdl2-ttf-dev
            sudo apt-get install libsdl2-2.0-0 libsdl2-dev
  
        - name: Build project
          run: |
            cmake -B build -S .
            cmake --build build
        - name: run
          run: |
          
        

      
